### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by ekardon** [rparelius/xml2JSON#4]
I would like to have an option to bypass some tags for example

`<points>
  <point>4</point>
  <point>5</point>
</points`
as
`points = [4, 5]` instead of `points = {point=[4, 5]}`

Would it be possible?

**Comment by rparelius** [comment]
That's an interesting idea, it should be possible. Let me look at the code and see what changes would be required to allow that.

**Comment by rparelius** [comment]
Hi @ekardon ,

I believe that I have a solution to your issue. I am adding several new features that can be used in concert to achieve the desired state:

1)  "move" option: accepts tuples of: an xpath query to match elements & an xpath query relative to the matched element of where to move it.

2) "rename" option: accepts tuples of: xpath query to match elements & w/ a string of the new tag value

here is an example:

```
>>> xml = """
... <root>
...   <points>
...     <point>4</point>
...     <point>5</point>
...   </points>
... </root>"""
>>> 
>>> 
>>> original = convert(xml)
>>> pp(original)
{'root': {'points': {'point': ['4', '5']}}}
>>> 
>>> 
>>> new = convert(xml, move=(".//point", "./../.."), rename=[(".//points", "ignore"), (".//point", "points")], ignore=".//ignore")
>>> pp(new)
{'root': {'points': ['4', '5']}}
```

as you can see, first we move the 'point' elements 2 levels up relative to their original position, essentially putting them alongside the original 'points' element that they were under. Then we rename the 'points' element to 'ignore', and rename 'point' to 'points', then we ignore the element 'ignore'.

It looks a little complicated, but I want the library to be as flexible as possible, so it can accommodate features such as what you requested, as well as a host of others.

Let me know what you think. I will be updating the code sometime today/tomorrow

**Comment by rparelius** [comment]
@ekardon, I have released ver. 0.2.5 which incorporates the new 'move' and 'rename' options which should accommodate your request, as shown above. Just update to the latest version through pip and you should be set.
